import { ComponentFixture, TestBed } from '@angular/core/testing';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideRouter } from '@angular/router';

import { CommercialClientModalComponent } from './commercial-client-modal.component';
import { ContractContactRole } from '../../../services/contract.service';
import { environment } from '../../../../environments/environment';

const CREATE_URL = `${environment.apiUrl}/crm/contract-directory/clients`;
const BUSINESS_URL = `${environment.apiUrl}/admin/business-customers`;

/**
 * The "New Commercial Client" modal — creating a client with NO contract.
 *
 * Two things this file pins, both of which are the reason the modal exists at all:
 *
 *  1. A client is created on its own. Nothing else is generated on the way past — the request
 *     goes to the contract DIRECTORY, not to the contract endpoint, so no agreement and no DCC
 *     number can be produced by using it.
 *  2. The linked business account is only ever what staff explicitly chose. It is optional, and
 *     it is never derived from an email address that happens to match one — that link grants
 *     access to a company's contracts.
 */
describe('CommercialClientModalComponent', () => {
  let component: CommercialClientModalComponent;
  let fixture: ComponentFixture<CommercialClientModalComponent>;
  let httpMock: HttpTestingController;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [CommercialClientModalComponent],
      providers: [provideHttpClient(), provideHttpClientTesting(), provideRouter([])]
    }).compileComponents();

    fixture = TestBed.createComponent(CommercialClientModalComponent);
    component = fixture.componentInstance;
    httpMock = TestBed.inject(HttpTestingController);

    fixture.componentRef.setInput('open', true);
    fixture.detectChanges();

    // Opening loads the business-account picker. Answered with one account whose email is
    // deliberately the same one the tests below type as the client's billing address.
    httpMock.expectOne(BUSINESS_URL).flush([
      {
        userId: 55, fullName: 'Casey Client', firstName: 'Casey', lastName: 'Client',
        email: 'accounts@chicktastic.invalid', phone: '7185550123',
        address: '1569 Flatbush Ave.', city: 'Brooklyn', state: 'NY', zip: '11210'
      }
    ]);
  });

  afterEach(() => httpMock.verify());

  const fillCompany = () => {
    component.form.legalEntityName = 'Chick Tastic LLC';
    component.form.principalAddress = '1569 Flatbush Ave.';
    component.form.city = 'Brooklyn';
    component.form.state = 'NY';
    component.form.zip = '11210';
  };

  const created = (id = 91) => ({
    id, legalEntityName: 'Chick Tastic LLC', entityType: 'a limited liability company',
    principalAddress: '1569 Flatbush Ave.', city: 'Brooklyn', state: 'NY', zip: '11210',
    isActive: true, sourceUserId: null, serviceLocations: [], contacts: []
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  describe('a client is created without a contract', () => {
    it('posts to the client directory and never to the contract endpoint', () => {
      fillCompany();
      component.submit();

      const request = httpMock.expectOne(CREATE_URL);
      expect(request.request.method).toBe('POST');
      expect(request.request.body.legalEntityName).toBe('Chick Tastic LLC');

      // Nothing else may be generated by creating a client.
      httpMock.expectNone(`${environment.apiUrl}/crm/contracts`);

      request.flush(created());
    });

    it('emits the created client and closes', () => {
      const emitted: number[] = [];
      let closed = 0;
      component.created.subscribe(c => emitted.push(c.id));
      component.closed.subscribe(() => closed++);

      fillCompany();
      component.submit();
      httpMock.expectOne(CREATE_URL).flush(created(91));

      expect(emitted).toEqual([91]);
      expect(closed).toBe(1);
    });

    it('sends neither a contact nor a location when they were left blank', () => {
      fillCompany();
      component.submit();

      const request = httpMock.expectOne(CREATE_URL);
      const body = request.request.body;
      expect(body.billingContact).toBeNull();
      expect(body.serviceLocation).toBeNull();

      request.flush(created());
    });

    it('sends the billing contact as a client signer when both names are given', () => {
      fillCompany();
      component.form.contactFirstName = 'Casey';
      component.form.contactLastName = 'Client';
      component.form.contactEmail = 'casey@chicktastic.invalid';
      component.submit();

      const request = httpMock.expectOne(CREATE_URL);
      const body = request.request.body;
      expect(body.billingContact.firstName).toBe('Casey');
      expect(body.billingContact.role).toBe(ContractContactRole.ClientSigner);

      request.flush(created());
    });

    it('copies the company address into the location when "same as company" is ticked', () => {
      fillCompany();
      component.form.addLocation = true;
      component.form.sameAsCompany = true;
      component.form.businessBrand = 'Chick Tastic';
      component.submit();

      const request = httpMock.expectOne(CREATE_URL);
      const body = request.request.body;
      expect(body.serviceLocation.address).toBe('1569 Flatbush Ave.');
      expect(body.serviceLocation.city).toBe('Brooklyn');
      // The trading name rides on the location because a client row has no DBA column.
      expect(body.serviceLocation.businessBrand).toBe('Chick Tastic');

      request.flush(created());
    });
  });

  describe('the linked business account', () => {
    it('is optional — a client saves with none', () => {
      fillCompany();
      component.submit();

      const request = httpMock.expectOne(CREATE_URL);
      expect(request.request.body.sourceUserId).toBeNull();
      request.flush(created());
    });

    it('is NEVER inferred from a billing email that matches an account', () => {
      fillCompany();
      // The exact address of the business account loaded above. Typing it must link nothing:
      // the link opens that customer's My Contracts area, so it is staff's decision alone.
      component.form.noticeEmail = 'accounts@chicktastic.invalid';
      component.submit();

      const request = httpMock.expectOne(CREATE_URL);
      expect(request.request.body.sourceUserId).toBeNull();
      request.flush(created());
    });

    it('is sent when an account was explicitly chosen', () => {
      fillCompany();
      component.form.sourceUserId = 55;
      component.submit();

      const request = httpMock.expectOne(CREATE_URL);
      expect(request.request.body.sourceUserId).toBe(55);
      request.flush(created());
    });

    it('fills blank company fields from the account but never the legal entity name', () => {
      component.form.sourceUserId = 55;
      component.form.legalEntityName = '';
      component.onSourceUserSelected();

      expect(component.form.city).toBe('Brooklyn');
      expect(component.form.zip).toBe('11210');
      // A business is not its owner. Guessing "Casey Client LLC" is worse than leaving it empty.
      expect(component.form.legalEntityName).toBe('');
    });

    it('never overwrites something the admin already typed', () => {
      component.form.principalAddress = '9 Somewhere Else Ave.';
      component.form.sourceUserId = 55;
      component.onSourceUserSelected();

      expect(component.form.principalAddress).toBe('9 Somewhere Else Ave.');
    });
  });

  describe('validation', () => {
    it('refuses to submit without a legal entity name', () => {
      component.form.principalAddress = '1569 Flatbush Ave.';
      component.form.city = 'Brooklyn';
      component.form.zip = '11210';

      expect(component.canSubmit).toBeFalse();
      component.submit();

      expect(component.errorMessage).toContain('legal entity name');
      httpMock.expectNone(CREATE_URL);
    });

    it('names a missing "@" rather than saying "invalid email"', () => {
      fillCompany();
      component.form.noticeEmail = 'accountschicktastic.invalid';

      component.submit();

      expect(component.errorMessage).toContain('@');
      httpMock.expectNone(CREATE_URL);
    });

    it('rejects half a billing contact', () => {
      fillCompany();
      component.form.contactFirstName = 'Casey';

      component.submit();

      expect(component.errorMessage).toContain('first and last name');
      httpMock.expectNone(CREATE_URL);
    });

    it('releases the button after a failed save', () => {
      fillCompany();
      component.submit();

      httpMock.expectOne(CREATE_URL).flush(
        { message: 'That customer is not flagged as a business.' },
        { status: 400, statusText: 'Bad Request' });

      // finalize, not complete: an HTTP error never reaches complete, which is how a failed save
      // used to leave the form stuck on "Creating…".
      expect(component.saving).toBeFalse();
      expect(component.errorMessage).toContain('not flagged as a business');
    });
  });

  /**
   * EDIT MODE. Opened with a client, the same form saves it back — and two things must be true
   * that are not true on create: the roster call for business accounts is not made (a saved
   * client's link is owned by the business flag on that account), and `sourceUserId` is not sent.
   */
  describe('editing an existing client', () => {
    const EXISTING = {
      id: 91,
      legalEntityName: 'Chick Tastic LLC',
      entityType: 'a limited liability company',
      formationState: 'New York',
      principalAddress: '1569 Flatbush Ave.',
      city: 'Brooklyn',
      state: 'NY',
      zip: '11210',
      noticeEmail: 'accounts@chicktastic.invalid',
      billingEmail: 'casey@chicktastic.invalid',
      billingPhone: '7185550123',
      billingContactFirstName: 'Casey',
      billingContactLastName: 'Client',
      billingContactTitle: 'Owner',
      primaryLocation: {
        id: 910, businessBrand: 'Chick Tastic', locationName: 'Flatbush',
        address: '1569 Flatbush Ave.', city: 'Brooklyn', state: 'NY', zip: '11210'
      },
      locations: [{ id: 910, label: 'Flatbush', address: '1569 Flatbush Ave., Brooklyn, NY 11210' }],
      contracts: [{ id: 900, contractNumber: 'DCC-2026-11112222', statusLabel: 'Fully signed' }],
      isActive: true,
      invoiceCount: 2,
      sourceUserId: 55,
      linkedAccountName: 'Casey Client',
      linkedAccountEmail: 'casey.login@example.invalid'
    } as any;

    const openEditing = () => {
      // Re-open with a client. The beforeEach above already flushed the create-mode roster call.
      fixture.componentRef.setInput('open', false);
      fixture.detectChanges();
      fixture.componentRef.setInput('client', EXISTING);
      fixture.componentRef.setInput('open', true);
      fixture.detectChanges();
    };

    it('fills the form from the saved client, field by field', () => {
      openEditing();

      expect(component.isEdit).toBeTrue();
      expect(component.form.legalEntityName).toBe('Chick Tastic LLC');
      expect(component.form.noticeEmail).toBe('accounts@chicktastic.invalid');
      expect(component.form.contactFirstName).toBe('Casey');

      // From primaryLocation's raw fields, never re-parsed out of the formatted display string.
      expect(component.form.addLocation).toBeTrue();
      expect(component.form.businessBrand).toBe('Chick Tastic');
      expect(component.form.locationAddress).toBe('1569 Flatbush Ave.');
      expect(component.form.sameAsCompany).toBeFalse();
    });

    it('shows the linked account and the contract count', () => {
      openEditing();

      expect(component.isLinked).toBeTrue();
      expect(component.linkedAccountName).toBe('Casey Client');
      // The account's LOGIN address, deliberately different from the billing one and shown beside
      // it rather than merged into it.
      expect(component.linkedAccountEmail).toBe('casey.login@example.invalid');
      expect(component.contractCount).toBe(1);
    });

    it('does not load the business-account picker', () => {
      openEditing();

      // Which account a saved client belongs to is not editable here.
      httpMock.expectNone(BUSINESS_URL);
    });

    it('PUTs to the client and never sends sourceUserId', () => {
      openEditing();
      component.form.legalEntityName = 'Chick Tastic Holdings LLC';

      component.submit();

      const request = httpMock.expectOne(CREATE_URL + '/91');
      expect(request.request.method).toBe('PUT');
      expect(request.request.body.legalEntityName).toBe('Chick Tastic Holdings LLC');
      expect(request.request.body.sourceUserId).toBeUndefined();

      request.flush(created(91));
    });

    it('emits saved, not created', () => {
      openEditing();

      const saved: number[] = [];
      const createdIds: number[] = [];
      component.saved.subscribe(id => saved.push(id));
      component.created.subscribe(c => createdIds.push(c.id));

      component.submit();
      httpMock.expectOne(CREATE_URL + '/91').flush(created(91));

      expect(saved).toEqual([91]);
      expect(createdIds).toEqual([]);
    });

    it('starts clean again when reopened for a new client', () => {
      openEditing();

      fixture.componentRef.setInput('open', false);
      fixture.detectChanges();
      fixture.componentRef.setInput('client', null);
      fixture.componentRef.setInput('open', true);
      fixture.detectChanges();

      expect(component.isEdit).toBeFalse();
      expect(component.form.legalEntityName).toBe('');
      expect(component.contractCount).toBe(0);
    });
  });
});
