import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';
import { provideRouter } from '@angular/router';
import { SocialAuthServiceConfig } from '@abacritt/angularx-social-login';

/**
 * Shared TestBed providers for the scaffolded "should create" specs.
 *
 * These specs were generated by `ng generate` and never had DI wiring added, so
 * every one of them failed with NullInjectorError. This is the boilerplate they
 * were always missing:
 *
 *  - HttpClient (+ testing backend) — nearly every service in the app injects it.
 *  - Router/ActivatedRoute — components that read route params or use routerLink.
 *  - SocialAuthServiceConfig — AuthService injects SocialAuthService, whose config
 *    is provided under a STRING token in app.config.ts (not the class token), so
 *    the test double has to match that token exactly.
 *
 * Import as `providers: [...testProviders]`. Specs that need real behaviour
 * should override individual providers rather than extending this list.
 */
export const testProviders = [
  provideHttpClient(),
  provideHttpClientTesting(),
  provideRouter([]),
  {
    provide: 'SocialAuthServiceConfig',
    useValue: {
      autoLogin: false,
      providers: [],
      onError: () => {},
    } as SocialAuthServiceConfig,
  },
];
