/*
 * GENERATED by scripts/generate-icons.mjs from scripts/icons.config.json - do not edit by hand.
 * Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0)
 */
import type { IconDefinition } from '../icon-definition';

export const faCheck: IconDefinition = { width: 448, height: 512, path: 'M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z' };
