/*
 * GENERATED by scripts/generate-icons.mjs from scripts/icons.config.json - do not edit by hand.
 * Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0)
 */
import type { IconDefinition } from '../icon-definition';

export const faExclamation: IconDefinition = { width: 128, height: 512, path: 'M96 64c0-17.7-14.3-32-32-32S32 46.3 32 64l0 256c0 17.7 14.3 32 32 32s32-14.3 32-32L96 64zM64 480a40 40 0 1 0 0-80 40 40 0 1 0 0 80z' };
