// AUTO-GENERATED by scripts/responsive-images.mjs - do not edit by hand.
// Re-run `npm run images:responsive` after changing scripts/responsive-images.config.json.

export interface ResponsiveImageVariant {
  readonly width: number;
  readonly url: string;
}

/** Original public URL -> its generated variants, ascending by width. */
export const RESPONSIVE_IMAGES: Readonly<Record<string, readonly ResponsiveImageVariant[]>> = {
  '/images/cabinet-cleaning-in-nyc.webp': [
    { width: 480, url: '/img/responsive/cabinet-cleaning-in-nyc-480.4aea521b.webp' },
    { width: 800, url: '/img/responsive/cabinet-cleaning-in-nyc-800.a02954fc.webp' },
    { width: 1200, url: '/img/responsive/cabinet-cleaning-in-nyc-1200.8c935964.webp' },
    { width: 1600, url: '/img/responsive/cabinet-cleaning-in-nyc-1600.7b74bc98.webp' }
  ],
  '/images/couch-cleaning-in-nyc.webp': [
    { width: 480, url: '/img/responsive/couch-cleaning-in-nyc-480.5b531d3c.webp' },
    { width: 800, url: '/img/responsive/couch-cleaning-in-nyc-800.a4463334.webp' },
    { width: 1200, url: '/img/responsive/couch-cleaning-in-nyc-1200.d8745a5e.webp' },
    { width: 1600, url: '/img/responsive/couch-cleaning-in-nyc-1600.f9e3f37d.webp' }
  ],
  '/images/dream-cleaning-maids-in-nyc.webp': [
    { width: 480, url: '/img/responsive/dream-cleaning-maids-in-nyc-480.1794a876.webp' },
    { width: 800, url: '/img/responsive/dream-cleaning-maids-in-nyc-800.2859d0d6.webp' },
    { width: 1200, url: '/img/responsive/dream-cleaning-maids-in-nyc-1200.11c5b017.webp' },
    { width: 1600, url: '/img/responsive/dream-cleaning-maids-in-nyc-1600.2fceca82.webp' }
  ],
  '/images/post-construction-cleaning.webp': [
    { width: 480, url: '/img/responsive/post-construction-cleaning-480.3dc8ef89.webp' },
    { width: 800, url: '/img/responsive/post-construction-cleaning-800.730e501b.webp' }
  ],
  '/images/retail-showrooms.webp': [
    { width: 480, url: '/img/responsive/retail-showrooms-480.f79933b0.webp' },
    { width: 800, url: '/img/responsive/retail-showrooms-800.2301d9cb.webp' }
  ],
  '/images/medical-dental.webp': [
    { width: 480, url: '/img/responsive/medical-dental-480.2dbcab31.webp' },
    { width: 800, url: '/img/responsive/medical-dental-800.1881df18.webp' }
  ],
  '/images/restaurants-cafes.webp': [
    { width: 480, url: '/img/responsive/restaurants-cafes-480.225d6cc6.webp' },
    { width: 800, url: '/img/responsive/restaurants-cafes-800.11259cc1.webp' }
  ],
  '/images/gyms-studios.webp': [
    { width: 480, url: '/img/responsive/gyms-studios-480.8287ca3d.webp' },
    { width: 800, url: '/img/responsive/gyms-studios-800.2e4f9a0a.webp' }
  ],
  '/images/building-common-areas.webp': [
    { width: 480, url: '/img/responsive/building-common-areas-480.95b74cf2.webp' },
    { width: 800, url: '/img/responsive/building-common-areas-800.cf686cb2.webp' }
  ],
  '/images/house-cleaning-service-nyc.webp': [
    { width: 320, url: '/img/responsive/house-cleaning-service-nyc-320.37a06102.webp' },
    { width: 480, url: '/img/responsive/house-cleaning-service-nyc-480.6e787647.webp' },
    { width: 680, url: '/img/responsive/house-cleaning-service-nyc-680.29bbbe3f.webp' },
    { width: 853, url: '/images/house-cleaning-service-nyc.webp' }
  ],
  '/images/kitchen-cleaning-in-nyc.webp': [
    { width: 320, url: '/img/responsive/kitchen-cleaning-in-nyc-320.428b52ec.webp' },
    { width: 480, url: '/img/responsive/kitchen-cleaning-in-nyc-480.a5ece912.webp' },
    { width: 680, url: '/img/responsive/kitchen-cleaning-in-nyc-680.63664fb0.webp' },
    { width: 853, url: '/images/kitchen-cleaning-in-nyc.webp' }
  ],
  '/images/apartment-cleaning-service-nyc.webp': [
    { width: 320, url: '/img/responsive/apartment-cleaning-service-nyc-320.69d220d0.webp' },
    { width: 480, url: '/img/responsive/apartment-cleaning-service-nyc-480.4b08575b.webp' },
    { width: 680, url: '/img/responsive/apartment-cleaning-service-nyc-680.a8ba9472.webp' },
    { width: 853, url: '/images/apartment-cleaning-service-nyc.webp' }
  ],
  '/images/deep-cleaning-service-nyc.webp': [
    { width: 320, url: '/img/responsive/deep-cleaning-service-nyc-320.1078c588.webp' },
    { width: 480, url: '/img/responsive/deep-cleaning-service-nyc-480.317da2f0.webp' },
    { width: 533, url: '/images/deep-cleaning-service-nyc.webp' }
  ],
  '/images/house-cleaning-service-nyc-2.webp': [
    { width: 320, url: '/img/responsive/house-cleaning-service-nyc-2-320.c0586fe9.webp' },
    { width: 480, url: '/img/responsive/house-cleaning-service-nyc-2-480.37fdc08d.webp' },
    { width: 532, url: '/images/house-cleaning-service-nyc-2.webp' }
  ],
  '/images/house-cleaning-service-nyc-3.webp': [
    { width: 320, url: '/img/responsive/house-cleaning-service-nyc-3-320.ad85bd8e.webp' },
    { width: 480, url: '/img/responsive/house-cleaning-service-nyc-3-480.b79dce47.webp' },
    { width: 533, url: '/images/house-cleaning-service-nyc-3.webp' }
  ],
  '/images/house-cleaning-service-nyc-4.webp': [
    { width: 320, url: '/img/responsive/house-cleaning-service-nyc-4-320.62165dff.webp' },
    { width: 480, url: '/img/responsive/house-cleaning-service-nyc-4-480.6de241c7.webp' },
    { width: 533, url: '/images/house-cleaning-service-nyc-4.webp' }
  ],
  '/images/airbn-cleaning-service-nyc.webp': [
    { width: 320, url: '/img/responsive/airbn-cleaning-service-nyc-320.d35dd62f.webp' },
    { width: 480, url: '/img/responsive/airbn-cleaning-service-nyc-480.dc96c143.webp' },
    { width: 533, url: '/images/airbn-cleaning-service-nyc.webp' }
  ],
  '/images/laundry-service-nyc.webp': [
    { width: 320, url: '/img/responsive/laundry-service-nyc-320.a6fcf165.webp' },
    { width: 480, url: '/img/responsive/laundry-service-nyc-480.fdc642c2.webp' },
    { width: 533, url: '/images/laundry-service-nyc.webp' }
  ],
  '/images/heavy-codition-cleaning-service-in-nyc.webp': [
    { width: 320, url: '/img/responsive/heavy-codition-cleaning-service-in-nyc-320.0dc75263.webp' },
    { width: 480, url: '/img/responsive/heavy-codition-cleaning-service-in-nyc-480.a0759b19.webp' },
    { width: 600, url: '/images/heavy-codition-cleaning-service-in-nyc.webp' }
  ],
  '/images/move-in-out-cleaning.webp': [
    { width: 320, url: '/img/responsive/move-in-out-cleaning-320.eb729383.webp' },
    { width: 480, url: '/img/responsive/move-in-out-cleaning-480.ecc81083.webp' },
    { width: 533, url: '/images/move-in-out-cleaning.webp' }
  ],
  '/images/post-construction-cleaning-3.webp': [
    { width: 320, url: '/img/responsive/post-construction-cleaning-3-320.ab9d9dc1.webp' },
    { width: 480, url: '/img/responsive/post-construction-cleaning-3-480.84c20a06.webp' },
    { width: 533, url: '/images/post-construction-cleaning-3.webp' }
  ],
  '/images/deep-cleaning2.webp': [
    { width: 320, url: '/img/responsive/deep-cleaning2-320.ba79dc30.webp' },
    { width: 480, url: '/img/responsive/deep-cleaning2-480.4398a1db.webp' },
    { width: 533, url: '/images/deep-cleaning2.webp' }
  ],
  '/images/filthy-cleaning-2.webp': [
    { width: 320, url: '/img/responsive/filthy-cleaning-2-320.9774837a.webp' },
    { width: 480, url: '/img/responsive/filthy-cleaning-2-480.335027a7.webp' },
    { width: 504, url: '/images/filthy-cleaning-2.webp' }
  ],
  '/images/deep-cleaning.webp': [
    { width: 320, url: '/img/responsive/deep-cleaning-320.dd0b6c80.webp' },
    { width: 449, url: '/images/deep-cleaning.webp' }
  ],
  '/images/filthy-cleaning.webp': [
    { width: 320, url: '/img/responsive/filthy-cleaning-320.35464ba6.webp' },
    { width: 450, url: '/images/filthy-cleaning.webp' }
  ],
  '/images/custom-cleaning-3.webp': [
    { width: 320, url: '/img/responsive/custom-cleaning-3-320.ef02c8cd.webp' },
    { width: 450, url: '/images/custom-cleaning-3.webp' }
  ],
  '/images/kitchen-cleaning-2.webp': [
    { width: 320, url: '/img/responsive/kitchen-cleaning-2-320.c5e53b71.webp' },
    { width: 450, url: '/images/kitchen-cleaning-2.webp' }
  ],
  '/images/kitchen-deep-cleaning.webp': [
    { width: 320, url: '/img/responsive/kitchen-deep-cleaning-320.66122000.webp' },
    { width: 450, url: '/images/kitchen-deep-cleaning.webp' }
  ],
  '/images/residential-cleaning.webp': [
    { width: 320, url: '/img/responsive/residential-cleaning-320.0442ef5d.webp' },
    { width: 449, url: '/images/residential-cleaning.webp' }
  ]
};

/** Original public URL -> width / height of the source (what object-fit: cover crops from). */
export const RESPONSIVE_IMAGE_RATIOS: Readonly<Record<string, number>> = {
  '/images/cabinet-cleaning-in-nyc.webp': 1.5,
  '/images/couch-cleaning-in-nyc.webp': 1.5,
  '/images/dream-cleaning-maids-in-nyc.webp': 1.5,
  '/images/post-construction-cleaning.webp': 1.5527,
  '/images/retail-showrooms.webp': 0.8003,
  '/images/medical-dental.webp': 0.8003,
  '/images/restaurants-cafes.webp': 0.8003,
  '/images/gyms-studios.webp': 0.8003,
  '/images/building-common-areas.webp': 0.8003,
  '/images/house-cleaning-service-nyc.webp': 0.6664,
  '/images/kitchen-cleaning-in-nyc.webp': 0.6664,
  '/images/apartment-cleaning-service-nyc.webp': 0.6664,
  '/images/deep-cleaning-service-nyc.webp': 0.6663,
  '/images/house-cleaning-service-nyc-2.webp': 0.665,
  '/images/house-cleaning-service-nyc-3.webp': 0.6663,
  '/images/house-cleaning-service-nyc-4.webp': 0.6663,
  '/images/airbn-cleaning-service-nyc.webp': 0.6663,
  '/images/laundry-service-nyc.webp': 0.6663,
  '/images/heavy-codition-cleaning-service-in-nyc.webp': 2,
  '/images/move-in-out-cleaning.webp': 1.7767,
  '/images/post-construction-cleaning-3.webp': 1.7767,
  '/images/deep-cleaning2.webp': 1.7767,
  '/images/filthy-cleaning-2.webp': 1.68,
  '/images/deep-cleaning.webp': 1.4967,
  '/images/filthy-cleaning.webp': 1.5,
  '/images/custom-cleaning-3.webp': 1.5,
  '/images/kitchen-cleaning-2.webp': 1.5,
  '/images/kitchen-deep-cleaning.webp': 1.5,
  '/images/residential-cleaning.webp': 1.4967
};
