#!/usr/bin/env node
/**
 * Generates the inline-SVG icon set the public pages use instead of the Font Awesome webfont.
 *
 *   npm run icons
 *
 * Reads the glyphs straight out of @fortawesome/fontawesome-free (the same package the webfont
 * comes from), so an icon drawn here is the exact shape the font used to draw.
 *
 * OUTPUTS
 *   - `glyphDir`: one module per icon (`glyphs/faCircleCheck.ts` exporting `faCircleCheck`),
 *     rendered with <i [appIcon]="..."> (src/app/shared/icons/icon.component.ts). Components
 *     import each icon from its own module:
 *       import { faCircleCheck } from '../shared/icons/glyphs/faCircleCheck';
 *     One FILE per icon is what makes a page bundle only the icons it imports. The production
 *     build assigns code to chunks per file and follows every import of a file it includes, so
 *     the set used to live in one `icons.ts` - and later behind a re-exporting barrel - put every
 *     icon used anywhere in the app into the initial bundle of every page. Don't add a barrel.
 *   - `scssOutput`: data-URI helpers for the few icons drawn from CSS pseudo-elements
 *     (`cssIcons`), where there is no element to put an <svg> in.
 *
 * To add an icon: append its Font Awesome name to `icons.solid` / `icons.brands` (or `cssIcons`)
 * in scripts/icons.config.json and re-run. Aliases are accepted ("times", "check-circle") and
 * resolved to the canonical name, which is what the constant is named after.
 *
 * Admin, CRM, cleaner portal and profile pages still use the Font Awesome webfont, loaded on
 * demand by src/app/shared/icons/font-awesome.loader.ts. Nothing here affects them.
 */

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONFIG_PATH = path.join(PROJECT_ROOT, 'scripts', 'icons.config.json');
const FA_ROOT = path.join(PROJECT_ROOT, 'node_modules', '@fortawesome', 'fontawesome-free');

const config = JSON.parse(await readFile(CONFIG_PATH, 'utf8'));
const families = JSON.parse(await readFile(path.join(FA_ROOT, 'metadata', 'icon-families.json'), 'utf8'));
const faVersion = JSON.parse(await readFile(path.join(FA_ROOT, 'package.json'), 'utf8')).version;

const canonical = {};
for (const [name, icon] of Object.entries(families)) {
  canonical[name] = name;
  for (const alias of icon.aliases?.names ?? []) canonical[alias] ??= name;
}

function resolve(style, requested) {
  const name = canonical[requested];
  const svg = name && families[name].svgs?.classic?.[style];
  if (!svg) throw new Error(`Font Awesome ${faVersion} has no ${style} icon named "${requested}"`);
  const pathData = Array.isArray(svg.path) ? svg.path.join(' ') : svg.path;
  return { name, width: svg.width, height: svg.height, path: pathData };
}

const constantName = name => 'fa' + name.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('');

const LICENSE = `Font Awesome Free ${faVersion} by @fontawesome - https://fontawesome.com\n * License - https://fontawesome.com/license/free (Icons: CC BY 4.0)`;

/** Writes `lines`, keeping the line ending the file already has (some outputs are CRLF). */
async function writeLines(file, lines) {
  let eol = '\n';
  try {
    if ((await readFile(file, 'utf8')).includes('\r\n')) eol = '\r\n';
  } catch { /* new file */ }
  await writeFile(file, lines.join(eol) + eol);
}

// ---- TypeScript constants ------------------------------------------------------------------
const HEADER = [
  '/*',
  ' * GENERATED by scripts/generate-icons.mjs from scripts/icons.config.json - do not edit by hand.',
  ` * ${LICENSE}`,
  ' */'
];
const glyphDir = path.join(PROJECT_ROOT, config.glyphDir);
// Start from an empty glyphs/ so an icon removed from the config leaves no module behind.
await rm(glyphDir, { recursive: true, force: true });
await mkdir(glyphDir, { recursive: true });

const seen = new Set();
for (const style of ['solid', 'brands']) {
  for (const requested of config.icons[style] ?? []) {
    const icon = resolve(style, requested);
    const constant = constantName(icon.name);
    if (seen.has(constant)) throw new Error(`Duplicate icon constant ${constant}`);
    seen.add(constant);
    const glyph = [
      ...HEADER,
      "import type { IconDefinition } from '../icon-definition';",
      '',
      `export const ${constant}: IconDefinition = { width: ${icon.width}, height: ${icon.height}, path: '${icon.path}' };`
    ];
    await writeFile(path.join(glyphDir, `${constant}.ts`), glyph.join('\n') + '\n');
  }
}
const written = (await readdir(glyphDir)).length;
if (written !== seen.size) throw new Error(`Expected ${seen.size} glyph modules, found ${written}`);

// ---- SCSS data-URI helpers -----------------------------------------------------------------
const scssLines = [
  '// GENERATED by scripts/generate-icons.mjs from scripts/icons.config.json - do not edit by hand.',
  `// ${LICENSE.replace('\n * ', '\n// ')}`,
  '//',
  '// icon-url($name)        -> url() of the glyph in black, for `mask-image` (colour comes from',
  '//                           `background-color`, so it can follow theme tokens).',
  '// icon-url($name, $fill) -> url() of the glyph painted $fill, for `background-image` on an',
  '//                           element whose own background is already in use (a coloured badge).',
  "// icon-ratio($name)      -> width / height of the glyph's box, as Font Awesome's webfont lays it out.",
  '',
  '@use "sass:map";',
  '@use "sass:math";',
  '@use "sass:string";',
  '',
  '$icon-glyphs: ('
];
for (const style of Object.keys(config.cssIcons ?? {})) {
  for (const requested of config.cssIcons[style]) {
    const icon = resolve(style, requested);
    scssLines.push(`  "${icon.name}": (width: ${icon.width}, height: ${icon.height}, path: "${icon.path}"),`);
  }
}
scssLines.push(
  ');',
  '',
  '@function _icon-glyph($name) {',
  '  $glyph: map.get($icon-glyphs, $name);',
  '  @if not $glyph { @error "Unknown CSS icon #{$name} - add it to cssIcons in scripts/icons.config.json"; }',
  '  @return $glyph;',
  '}',
  '',
  '@function icon-ratio($name) {',
  '  $glyph: _icon-glyph($name);',
  '  @return math.div(map.get($glyph, width), map.get($glyph, height));',
  '}',
  '',
  '@function icon-url($name, $fill: null) {',
  '  $glyph: _icon-glyph($name);',
  '  $w: map.get($glyph, width);',
  '  $h: map.get($glyph, height);',
  "  $fill-attr: '';",
  "  @if $fill { $fill-attr: \" fill='#{_icon-encode-color($fill)}'\"; }",
  "  @return url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='#{$w}' height='#{$h}' viewBox='0 0 #{$w} #{$h}'%3E%3Cpath#{$fill-attr} d='#{map.get($glyph, path)}'/%3E%3C/svg%3E\");",
  '}',
  '',
  '@function _icon-encode-color($color) {',
  '  $s: "#{$color}";',
  '  @if string.index($s, "#") == 1 { @return "%23" + string.slice($s, 2); }',
  '  @return $s;',
  '}',
  ''
);
await writeLines(path.join(PROJECT_ROOT, config.scssOutput), scssLines.slice(0, -1));

console.log(`Wrote ${seen.size} icon modules to ${config.glyphDir} and ${Object.values(config.cssIcons ?? {}).flat().length} CSS glyphs to ${config.scssOutput} (Font Awesome ${faVersion}).`);
